etc/gofer/plugins/katelloplugin.conf
Although, this needs some very obvious note in the upgrade docs for 2.1.1 to users that they need to regenerate their certificate RPM's as well in the upgrade case.
Renaming certificate locations is bad, especially when tools like katello-agent are relying on their location... :-1:
=> fixes #9403 - use correct certificate location

etc/gofer/plugins/katelloplugin.conf, katello-agent.spec, src/katello/agent/katelloplugin.py, test/test_plugin.py
Pulp 2.6 requires gofer 2.4.  The major version change of gofer requires the server and agent be on the same version.  gofer 2.4 is included in f21 on.
The *Plugin.cfg()* method changed to a property in gofer 2.
Better URL support in gofer 2 so amqps://<host> will default to the standard port for amqp ssl.
=> gofer 2.x compat.

etc/gofer/plugins/katelloplugin.conf, katello-agent.spec, src/katello/agent/katelloplugin.py, test/test_plugin.py
Based on: https://github.com/Katello/katello-agent/pull/17
Includes:
- Agent validates registration using the REST API.  This is part of the fix for leaking agent queues in qpid.
- Update the URL to specify the *proton* messaging adapter.
```
[jortel@localhost test]$ nosetests . --with-coverage --cover-package=katello.agent
..............................
Name                          Stmts   Miss  Cover   Missing
-----------------------------------------------------------
katello.agent                     0      0   100%   
katello.agent.katelloplugin     165      0   100%   
-----------------------------------------------------------
TOTAL                           165      0   100%   
----------------------------------------------------------------------
Ran 30 tests in 0.403s
OK
```
=> Agent changes for Sat 6.1

src/katello/agent/katelloplugin.py, test/test_plugin.py
In PR #18, the *attach* logic was changed to include validating the registration by making an API call to the server.  Because this could block, this logic was moved to an *Attach* thread to prevent blocking other plugins from being loaded in cases where the API was not available and had to be retried.  Unfortunately, this introduces a possible situation whereby the gofer request scheduler is started before the katello plugin has completely initialized (and available).  The effect is that pending RMI requests would fail to be dispatched to the plugin.  because it's not completely initialized.
The change in this PR ensures that the katello plugin is completely initialized before the plugin loader is permitted to continue.  This is essentially reverting back to the way it worked before #18. …
=> Agent registration fixes.

.gitignore, src/katello/agent/katelloplugin.py, test/test_plugin.py
Followed by candlepin-local.pem for backward compatibility and the
repo_ca_cert as fallback.
Requires https://github.com/Katello/puppet-certs/pull/62 to work properly.
=> Fixes #10670 - preffer the katello-default-ca.pem as the client ca cert

src/katello/agent/katelloplugin.py, test/test_plugin.py
The consumer gets sent this unsupported `Consumer.unregister()` call which causes a nasty traceback (see below) when you run `subscription-manager unregister`
I thought it might be nice for goferd service to stop, but there doesn't seem a way for a plugin to tell the goferd to exit. And besides, if the user immediately re-registers then the goferd would be stopped and they might not want that.  So I log a message, to try to be helpful.  The logs look nicer, at least.  Any other suggestions maybe?
Before:
```
May 20 17:50:19 cloud-qe-7 goferd: [INFO][worker-0] gofer.rmi.dispatcher:600 - call: Consumer.unregister() sn=d38f07cc-ec0f-4424-b005-759d81d8871f data=None
May 20 17:50:19 cloud-qe-7 goferd: [ERROR][worker-0] gofer.rmi.dispatcher:636 - {u'replyto': None, u'request': {u'classname': …
```
=> fixes #13957 - handle Consumer.unregister() call

src/katello/agent/katelloplugin.py, test/test_plugin.py
http://projects.theforeman.org/issues/18406
Mitigation of urlgrabber thread safety bug:1204825. 
I *think* we've identified the (3) possible threads using yum=>urlgrabber:
1. The main goferd plugin loader thread: init_plugin() => send_enabled_report().
2. The pmon "path monitoring" thread: redhat.repo changed => send_enabled_report()
3. The plugin worker thread: YUM update request.
By dispatching the `send_enabled_report()` through the plugin thread pool, 1 & 2 are eliminated.
urlgrabber bug: https://bugzilla.redhat.com/show_bug.cgi?id=1204825
=> fixes #18406 - mitigation for urlgrabber thread safety.

src/yum-plugins/enabled_repos_upload.py
Correctly spelled repositories in output message.  Fixes http://projects.theforeman.org/issues/20531
=> Fixes #20531 - Fix typo in upload message

bin/katello-enabled-repos-upload, bin/katello-package-upload
this makes the code compatible with Python < 2.7 (EL5: 2.4, EL6: 2.6)
=> Fixes #20702 - use optparse instead of argparse

.travis.yml, Makefile
this uses docker to run the code on el5, el6 and el7, thus ensuring the code is at least valid for those
this should prevent stuff like http://projects.theforeman.org/issues/20702 and http://projects.theforeman.org/issues/20404
example build can be seen at https://travis-ci.org/evgeni/katello-agent/builds/268312275
=> add some basic tests to ensure the code works on all supported OSes

extra/katello-agent-send.cron
I suspect this isn't working for some people because if it runs before the network is up, it will not work. 
I think we should either add this sleep or instead create a systemd-timer unit, with proper dependencies.
=> Fixes #22330 - Always run cron after reboot

bin/katello-tracer-upload, src/katello/tracer.py, src/yum-plugins/tracer_upload.py
The ./bin/katello-tracer-upload script wasn't updated in all the recent refactoring in this repo, and so the traceback in the issue was shown with no tracer info uploaded to Katello
Spin up a centos7 box and register it to some katello instance
```
vagrant up centos7
```
Checkout the master branch, and build the code:
```
cd src/
python setup.py install
```
Run the tracer script:
```
python -- ./bin/katello-tracer-upload
```
You should see 
```
Traceback (most recent call last):
File "bin/katello-tracer-upload", line 13, in <module>
main()
File "bin/katello-tracer-upload", line 10, in main
tracer_upload.upload_tracer_profile()
TypeError: upload_tracer_profile() takes exactly 2 arguments (0 given)
```
Check out this PR, rebuild the code, and run the tracer-upload script again - it should …
=> Fixes #23405 - Tracer executable throws error

images/Dockerfile.el6, src/katello/agent/goferd/legacy_plugin.py, test/test_katello/legacy_plugin_test.py, test/unittest_suite.py
You may want to test an el5 and el6 client. These changes will require some adjustments to the specfile which I'll handle after this is merged.
Basically, this code is duplicated so that we are less concerned with breaking it on older clients and when it comes times to drop support we can delete these added files.
Steps:
1. Provision system
2.  set up some repos
```
wget -O /etc/yum.repos.d/epel-rhsm.repo http://repos.fedorapeople.org/repos/candlepin/subscription-manager/epel-subscription-manager.repo
yum install https://fedorapeople.org/groups/katello/releases/yum/3.5/client/el6/x86_64/katello-client-repos-latest.rpm
```
3. yum install subscription-manager gofer python-pulp-agent-lib python-gofer-proton pulp-rpm-handlers
4. register the system to your katello
5. checkout this PR
```
yum …
```
=> Fixes #23459 - Restore legacy goferd plugin

src/katello/agent/goferd/legacy_plugin.py, src/katello/agent/goferd/plugin.py, test/test_katello/legacy_plugin_test.py, test/test_katello/test_plugin.py
https://projects.theforeman.org/issues/24006
To better deal with a plugin's queue disappearing, gofer 2.13 will reload the plugin when the condition is detected.  This gives the katello plugin the opportunity to determine if the host is registered and configure itself accordingly.
This is API compatible with gofer 2.7+.
The goferd reload behavior is planned to be backported to 2.11 as well.
=> Support reload on queue not exist.

src/katello/agent/pulp/libdnf.py, src/katello/agent/pulp/libyum.py
https://projects.theforeman.org/issues/24081
Should only process `patterns` when `advisories` are _not_ specified.  Regression introduced while cleaning up ported pulp code.
=> Fix errata install - upgrating unrelated packages.

src/katello/enabled_report.py, test/test_katello/data/repos/redhat.repo.with_vars, test/test_katello/test_enabled_report.py
Previously, repo baseurls were sent as-is from redhat.repo to
Satellite. This resulted in the client reporting it was subscribed to
repos that don't exist, since the URLs would have the literal string
`$releasever/$basearch` in it.
This commit adds dnf and yum code to populate `$releasever` and
`$basearch`. It will attempt to use DNF libraries first, and if that
raises an `ImportError`, it will try yum.
=> Fixes #24214 - fill in vars on repo URLs

src/dnf_plugins/tracer_upload.py, test/dnf_plugins/test_tracer_upload.py
This PR restores the tracer code for DNF removed by https://github.com/Katello/katello-host-tools/commit/89e62f5ef29e818b9aa80f348d8e5efe113e47e6.
Testing steps, from a fedora machine of some sort:
- register the client to your devel box, or elsewhere
- check out this pr on the client
- install some prereq packages: make python3-tracer subscription-manager
- run `make install` to install the code
- dnf plugin needs to be linked:
```
ll /usr/lib/python3.6/site-packages/dnf-plugins/tracer_upload.py
lrwxrwxrwx. 1 root root 57 Dec  6 17:55 /usr/lib/python3.6/site-packages/dnf-plugins/tracer_upload.py -> /root/katello-host-tools/src/dnf_plugins/tracer_upload.py
```
- run 'dnf katello-tracer-upload' to and check your rails log for a `PUT /rhsm/consumers/:uuid/tracer`
If you have any tracers the …
=> Fixes #25587 - Restore DNF tracer plugin

src/katello/utils.py, test/test_katello/test_packages.py, test/test_katello/test_utils.py, test/test_yum_plugins/test_enabled_repos_upload.py, test/unittest_suite.py
This code will automatically disable enabled_repos_upload and package_upload plugins when it detects that a subscription-manager supporting the same is installed.
There are many ways to test this, here's one:
1. spin up a katello-client, registered to some server
2. check out this PR on the client
3. symlink the previously installed katello utils.py to your git checkout of this PR to use the new code `/usr/lib/python2.7/site-packages/katello/utils.py`
If you're using subscription-manager >= 1.23 the package & repos plugins should not send data to the server after a yum transaction, but they will function as usual for lower versions.
=> Fixes #25725 - disable plugins if we have subman profiles

extra/katello-tracer-upload-dnf
many places (like our own cron file) reference the katello-tracer-upload
binary, but we don't actually build/ship that binary on dnf-based
distros.
=> add a katello-tracer-upload wrapper for the dnf plugin

src/katello/tracer.py
before:
```
[root@fedora28 katello-host-tools]# dnf install wget                                                    
Error Importing tracer! Is tracer installed?  
```
after:
```
[root@fedora28 src]# dnf install wget                                                                                                                                                             
Failed loading plugin: tracer_upload                                                                                                                                                               
Updating Subscription Management repositories.
This system is registered to Red Hat Subscription Management, but is not receiving updates. You can use subscription-manager to assign subscriptions.
Updating Subscription Management …
```
=> Fixes #26363 - Don't exit transaction when tracer plugin is broken

containers/assets/epel-el5-archive.repo, images/Dockerfile.el5, images/Dockerfile.el6, test-requirements.txt
Looks like el5 clients can't open SSL connections to yum.theforeman.org anymore. I found a patched wget so that packages can be fetched and installed via RPM. Not pretty but it works. I'm guessing our SSL ciphers changed.
The more concerning part is that whatever has changed on yum.theforeman.org basically breaks all support for el5 clients.
EL6 tests were failing b/c a newer mock library was getting pulled in.
=> Fix the builds

.travis.yml, images/Dockerfile.f30, images/Dockerfile.suseLeap42, src/zypper_plugins/package_upload.py, test/unittest_suite.py, test/zypper_plugins/test_package_upload.py
This PR:
- Adds a Fedora 30 image for tests
- Adds a Suse Leap 42 image for tests
- Adds the new images to the travis test matrix
- Adds tests for Zypper package upload plugin
Since we have 3 Zypper plugins now it's important to have this. While we actually support SLES only, it's not feasible - as far as I know - to get this working nearly as simply as using suse leap.
=> Add Suse Leap and Fedora 30 test containers

src/katello/agent/pulp/libdnf.py, test/test_katello/test_agent/test_pulp/test_libdnf.py
This commit ensures that the packages belonging to errata are upgraded
appropriately.
=> Fixes #26920 - Install errata via libdnf

.travis.yml, Makefile, images/Dockerfile.el5, images/Dockerfile.f31, src/katello/agent/goferd/plugin.py, test/test_katello/test_plugin.py
**To test**
Spin up a fedora30 client and register it to your katello
Install katello-agent from the nightly repos (3.5.1)
Observe that package actions (ie install package) via katello-agent does not complete successfully.
Apply the patch here to plugin.py and restart goferd. The previous package action should be picked up (journalctl -xaf) and any new package actions should succeed as normal
=> Fixes #28449 - katello-agent no qpid connection w/ gofer 3.0

src/katello/agent/pulp/libdnf.py, test/test_katello/test_agent/test_pulp/test_libdnf.py
The katello agent for libdnf based systems was ignoring the "update all
packages" call. It would see no patterns and not execute the update.
This commit fixes that by running an update all on empty pattern set.
=> Fixes #28909 - Enabled libdnf update all

test-requirements.txt
mock 4.0.0 broke our tests, so locking the version for now
https://github.com/testing-cabal/mock/issues/486
=> Fixes #28962 - Lock mock version < 4.0.0

src/katello/enabled_report.py
By setting the debuglevel to 0 we disable the `Loaded plugins: fastestmirror, product-id, subscription-manager` that `YumBase` would emit otherwise.
After applying this change the output would be:
```
Loaded plugins: enabled_repos_upload, fastestmirror, product-id, search-disabled-repos, subscription-manager
java-1.8.0-openjdk.x86_64                                                                                                                                        1:1.8.0.222.b10-1.el7_7                                                                                                                               updates
java-1.8.0-openjdk-headless.x86_64 …
```
=> fixes #27912 - Disable debug output from yum

src/katello/agent/pulp/libyum.py
Installing package from the UI for a yum client was not working:
```
May  4 15:57:29 katello-client goferd: [ERROR][worker-0] katello.agent.pulp.dispatcher:82 - InstallError: *:katello-host-tools-tracer.*: No package(s) available to install
```
This change is consistent with libdnf: https://github.com/Katello/katello-host-tools/blob/master/src/katello/agent/pulp/libdnf.py
**Witness the broken behavior**
- Register a content host such as katello-client and install katello-agent
- From the UI, navigate to the host details and go to Packages -> Actions
- Enter a package name such as katello-host-tools-tracer and 'Perform'
- Notice the task fails as shown above
**Test the fix**
- Update libyum.py on the client with the version from this PR (use 'raw')
`curl <url of libyum.py from this pr> > …
=> Fixes #29691 - Prevent generating invalid package patterns for yum

src/dnf_plugins/tracer_upload.py, src/yum-plugins/tracer_upload.py
This should be tested in conjunction with https://github.com/FrostyX/tracer/pull/141 and https://github.com/Katello/katello/pull/8712 to save time and make sure everything works together!
This requires a regression test of both EL7 and EL8 in this fashion:
- apply https://github.com/Katello/katello/pull/8712 your katello server
- register an EL7 client and subscribe to RHEL base
- install katello-host-tools-tracer on the client
- patch tracer and katello-host-tools-tracer with this code and https://github.com/FrostyX/tracer/pull/141
- upgrade some packages (tuned, auditd, kernel) which will create some traces (note them in the UI)
- run katello-tracer-upload - the traces should be virtually identical to what was already there
- run `tracer --user * -av` and compare the output to the UI - …
=> Fixes #29824 - Rely on Tracer to find affected packages for DNF

src/katello/agent/pulp/libdnf.py
When DNF is used via the API, the system configuration is not
loaded. This can cause OSes like Centos 8 stream to fail to
load repositories when doing variable substitution.
=> Fixes #32450: Load system configuration when calling dnf

src/setup.py
The release job failed for 4.0.0:
```
Invalid value for classifiers. Error: Classifiers ['License :: OSI Approved :: GNU General Puclic License (GPL)', 'Topic :: Content Management and Delivery'] are not valid classifiers.
```
So I fixed the typo in the GPL classifier and removed the completely invalid one
=> Release 4.0.1

extra/katello-tracer-upload.cron
katello-tracer-upload for debian/ubuntu uses deb_tracer.py and in the end "needrestart" is used. needrestart is in /usr/sbin/. On Debian/Ubuntu, "@reboot" jobs have only PATH=/usr/bin/ set. Therefore its necessary to set the PATH variable so that needrestart can be found.
=> Make sure commands used by katello-tracer-upload can be found

src/katello/agent/pulp/libdnf.py, test/test_katello/test_agent/test_pulp/test_libdnf.py
When installing an erratum via katello-agent on EL8 (with dnf), katello-agent tells libdnf to update the individual packages inside the erratum. Currently, it only passes the name, causing the latest RPM to be installed rather than the one in the erratum.  To fix this, I am appending the `evr` to the name to match the correct package.  The most ideal solution would be to use `dnf upgrade --minimal`, but `libdnf` doesn't seem to have Python bindings for that action.
To test:
1) `vagrant up rhel8` and register it to your Katello server.
2) Sync RHEL 8 AppStream + BaseOS.
3) Ensure that `tzdata-2022a-1.el8.noarch` and `tzdata-java-2022a-1.el8.noarch` are installed.
4) Locate the RHBA-2022:7067 and RHBA-2022:7404 errata in AppStream/BaseOS.  Note that the earlier one includes the `e` versions …
=> Fixes #35759 - specify package evr when updating via errata to match upgrade-minimal

src/katello/scripts.py
This isn't needed and triggers dependencies in RPM packaging that shoulnd't be there.
Fixes: 8c5b6c1ece2ef7ff76d781a2d5a41443c9ea0845
=> Remove shebang from library

src/katello/tracer/__init__.py
This now implements the pattern where it tries to define the collect_apps method and simply use that, without additional variables.
=> Refactor tracer loading to always define the same method

src/katello/tracer/SystemdDbus.py, src/katello/tracer/__init__.py, src/katello/tracer/dnf.py
Discussion, see: https://community.theforeman.org/t/tracer-for-dnf/35633?u=bernhard_suttner
=> Fixes #36973 - Use dnf needs-restarting to collect tracer information

src/setup.py
The change to using dnf needs-restarting is pretty major, so I'm bumping the Y version.
=> Bump version to 4.4.0

extra/81-tracer-upload-apt, extra/katello-tracer-upload.cron
The path to the tracer tool was adapted for EL variants: https://github.com/theforeman/foreman-packaging/blob/rpm/develop/packages/client/katello-host-tools/katello-host-tools.spec#L398
This commit adapts the same for Debian. Additionally, if the PATH variable is set, it doesn't make sense to provide the path to the katello-tracer-upload script.
=> Fix katello-tracer-upload path. (Refs #137)

src/katello/repos.py
In Python 2.5 context managers were added, which can help ensure open files are closed. EL 5 shipped with Python 2.4, but EL6 has Python 2.6 meaning we can now rely on this shiny new feature.
=> Rely on Python 2.5+ context managers

.github/workflows/pull_request.yml, images/Dockerfile.debian11, images/Dockerfile.el10, images/Dockerfile.el7, images/Dockerfile.suseLeap15, images/Dockerfile.suseLeap42, src/katello/constants.py, src/katello/tracer/__init__.py, src/katello/utils.py, test-requirements.txt, test/dnf-plugins/test_tracer_upload.py, test/dnf_support.py, test/test_katello/test_enabled_report.py, test/test_katello/test_repos.py, test/test_katello/test_tracer/test_tracer.py, test/test_yum_plugins/test_enabled_repos_upload.py, test/unittest_suite.py, test/zypper_plugins/test_enabled_repos_upload.py, test/zypper_plugins/test_package_upload.py, test/zypper_plugins/test_tracer_upload.py
- **don't set max-parallel 1, run all the tests in parallel**
- **fail-fast: false - run all tests even if some fail**
- **add EL10 testing**
- **use native unittest, unittest2 was a backport for pre 2.7 python**
- **stop using deprecated imp -- import and ImportError is enough**
- **properly skip DNF related tests when DNF is not available**
- **Add Debian 11 tests**
=> Add CentOS 10, Debian 11 and openSUSE 15 tests
